version: '3'

services:
  hackathon-server:
    container_name: 3am
    depends_on:
      - mongodb
    env_file:
      "backend/.env"
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped # set to always for deployment
  hackathon-frontend:
    container_name: 3am-frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped # set to always for deployment
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - db:/data/db # Create a volume for the DB.

volumes:
  db: